name: Delete branch on merge

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@v1.3.3
